server:
  port: 8001

spring:
  application:
    name: stream-provider
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.0.103
                port: 5672
                username: guest
                password: guest
      bindings:
        output:
          destination: springCloudBus
          content-type: application/json
          binder: defaultRabbit
