server:
  port: 8001

spring:
  application:
    name: user-provider
  datasource:
    url: jdbc:mysql://192.168.0.103:3306/demo
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
  #时间转换成毫秒
  jackson:
    serialization:
      write-dates-as-timestamps: true
#开启驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true


eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://localhost:7001/eureka/ #配置注册中心地址


#info:
#  app.name: user
#  build.artifactId: @project.artifactId@
#  build.version: @project.version@
#



