spring:
  profiles:
    active:
      -dev
---
server:
  port: 3001
spring:
  profiles: dev
  application:
    name: user-provider
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

---
spring:
  profiles: prod
  applicaiont: prod
